Repository ajaynegi45/Uttarakhand-Culture-NewUI, pull requests merged in 2024-10, with the labels that each got.

#76 Twiter icon changed and blue line removed
  README.md
  public/icons8-twitter-48 (1).png
  public/icons8-twitter-60.png
Labels: enhancement, status: ready for dev, hacktoberfest, gssoc, hacktoberfest-accepted, level1, gssoc-ext

#144 added custom favicon
  package-lock.json
  src/app/favicon.ico
  src/app/layout.tsx
Labels: good first issue, hacktoberfest, gssoc, hacktoberfest-accepted, level1, gssoc-ext

#150 Discord Server
  README.md
Labels: status: ready for dev, hacktoberfest, gssoc, hacktoberfest-accepted, level3, gssoc-ext

#225 Added Filtering Functionality and new locations to Trekking page
  src/app/trekking/location-detail.js
  src/app/trekking/page.tsx
  src/components/ui/TrekCard.module.css
Labels: enhancement, status: ready for dev, hacktoberfest, gssoc, hacktoberfest-accepted, level3, gssoc-ext

#227 scroll bar removed : #226 done
  src/app/globals.css
Labels: enhancement, status: ready for dev, hacktoberfest, gssoc, hacktoberfest-accepted, level1, gssoc-ext

#240 faq question enhanced
  src/components/Faq.tsx
Labels: enhancement, status: ready for dev, hacktoberfest, gssoc, hacktoberfest-accepted, level3, gssoc-ext
